### ISSUE TITLE
Error: no mixin named *

### ISSUE THREAD

**Issue by thomasfrobieter** [MarioAraque/atom-bourbon-snippets#7]
Hey, i´m new to atom, so this may totally be my mistake.

I cant get bourbon to work, installed it via Ruby gem (which is not necessary when using your plugin?), installed your plugin, but no bourbon mixin works.

I use sass-autocompile to compile my scss files.

Any ideas?

Thanks alot :)

**Comment by MarioAraque** [comment]
Hey @thomasfrobieter 

My plugin is to write bourbon mixins quickly. So you write your code in Atom, and them compile it via Gulp/Grunt/Webpack.

Unfortunately this place is to provide issues about the plugin, not Bourbon errors. Try reinstalling it, and check if bourbon is included correctly in your SASS file.

Hope you have a solution soon :)

Regards.
